# Generated by Django 3.2.7 on 2021-11-09 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsored',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='content',
            name='sponsor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.sponsor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='content_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
