# Generated by Django 3.2.7 on 2023-03-13 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230131_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmpsavepost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.influencerpost'),
        ),
        migrations.AlterField(
            model_name='cmpsavepost',
            name='who_saved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sponsor'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='is_verified',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencerpost',
            name='adfield',
            field=models.CharField(choices=[('Facebook Post', 'Facebook Post'), ('Facebook Story + Swipe Up', 'Facebook Story + Swipe Up'), ('Instagram Post', 'Instagram Post'), ('Instagram Reels', 'Instagram Reels'), ('Instagram Story + Swipe Up', 'Instagram Story + Swipe Up'), ('YouTube Shorts + Swipe Up', 'YouTube Shorts + Swipe Up'), ('YouTube Video', 'YouTube Video')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='is_verified',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
